# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 787a8e2039479e09cf5c3ab83cc1bad3430f355b688f8ddd1807d9503ef20741fa81bae6d6696f3ee9cfe2ca417484cd7b9606737202e00524f35769a74bfe6d

test:
  secret_key_base: 408c06ed9eae4668df953b0a49200927ab2e53e7461e10f1fb1c55580000efad64eae736accebffb868567ab1d4ee48fa2276a1476478940e101cc85335fc0d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
